### PR TITLE
Most transitions replaced with new vars. Circle back what to do with 'linear's and 'eases'.

### PR DESCRIPTION
**Pull request by msbeethoven**

### CODE REVIEW

**Comment by msbeethoven** [comment]
> @msbeethoven is there a reason why we're not standardizing the length of these transitions? I noticed most were between .2 and .3. It would be cleaner to have the variables include the length (and would probably a better user experience to standardize the length). You can leave off the "all" since that is the default and on a case-by-case basis add in transition properties like transform or opacity. Also - you don't need to specify opacity (for example) if that's the only thing changing when the transition is triggered.
> 
> If you guys wanted to keep it more granular or not deal with standardizing the length, then everything looks good!

@kimlarocca Thanks! I had a question about the length as well . When you save we don't need to specify opacity, that's because we had that covered in colors?

**Comment by kimlarocca** [comment]
@msbeethoven I meant you could simplify the CSS. It could be as simple as the following example:

.button {
  opacity: 1;
  transition: var(--animation-easing-standard);
  &:hover {
     opacity: var(--opacity-on-hover);
  }
}

If --animation-easing-standard included the length.

**Comment by kimlarocca** [comment]
As for your circle back on linear vs. easing, I'd say we should decide on a standard - either linear or eased - and stick with it for most animations.

**Comment by msbeethoven** [comment]
> transition-timing-function is for ease, linear, cubic-bezier, etc (not length) so setting that to your duration variables won't work. However, you can simplify all of this by doing:
> 
> `transition: var(--animation-easing-incoming) var(--animation-duration-fast);
> 
> Instead of
> 
> ```
> transition-timing-function: var(--animation-duration-fast);
> transition: var(--animation-easing-incoming);
> ```
> 
> (you can leave off "all")

Thanks! So how is this different than separating out the two rules, aka https://codepen.io/kimlarocca/pen/XWmVbKr ? Since the `animation-duration` rules are setting for cubic-bezier.

**Comment by kimlarocca** [comment]
I just separated them on codepen so you could see what was what ;) I updated the codepen so you can see them combined!

**Pull request merged**
